src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $FLYING_FROM;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $FLYING_TO;

    /**
     * @ORM\Column(type="date")
     */
    private $DEPARTING;

    /**
     * @ORM\Column(type="date")
     */
    private $Retour;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adults;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $children;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $travel_class;

    /**
     * @ORM\ManyToMany(targetEntity=Voyage::class, inversedBy="reservations")
     */
    private $voyage;

    public function __construct()
    {
        $this->voyage = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFLYINGFROM(): ?string
    {
        return $this->FLYING_FROM;
    }

    public function setFLYINGFROM(string $FLYING_FROM): self
    {
        $this->FLYING_FROM = $FLYING_FROM;

        return $this;
    }

    public function getFLYINGTO(): ?string
    {
        return $this->FLYING_TO;
    }

    public function setFLYINGTO(string $FLYING_TO): self
    {
        $this->FLYING_TO = $FLYING_TO;

        return $this;
    }

    public function getDEPARTING(): ?\DateTimeInterface
    {
        return $this->DEPARTING;
    }

    public function setDEPARTING(\DateTimeInterface $DEPARTING): self
    {
        $this->DEPARTING = $DEPARTING;

        return $this;
    }

    public function getRetour(): ?\DateTimeInterface
    {
        return $this->Retour;
    }

    public function setRetour(\DateTimeInterface $Retour): self
    {
        $this->Retour = $Retour;

        return $this;
    }

    public function getAdults(): ?string
    {
        return $this->adults;
    }

    public function setAdults(string $adults): self
    {
        $this->adults = $adults;

        return $this;
    }

    public function getChildren(): ?string
    {
        return $this->children;
    }

    public function setChildren(string $children): self
    {
        $this->children = $children;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getTravelClass(): ?string
    {
        return $this->travel_class;
    }

    public function setTravelClass(string $travel_class): self
    {
        $this->travel_class = $travel_class;

        return $this;
    }

    /**
     * @return Collection|Voyage[]
     */
    public function getVoyage(): Collection
    {
        return $this->voyage;
    }

    public function addVoyage(Voyage $voyage): self
    {
        if (!$this->voyage->contains($voyage)) {
            $this->voyage[] = $voyage;
        }

        return $this;
    }

    public function removeVoyage(Voyage $voyage): self
    {
        $this->voyage->removeElement($voyage);

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('FLYING_FROM')
            ->add('FLYING_TO')
            ->add('DEPARTING')
            ->add('Retour')
            ->add('adults')
            ->add('children')
            ->add('phone')
            ->add('travel_class')
            ->add('voyage')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Dompdf;
use Dompdf\Options;
/**
 * @Route("/reservation")
 */
class ReservationController extends AbstractController
{
    /**
     * @Route("/", name="reservation_index", methods={"GET"})
     */
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }
    /**
     * @Route("/pdf", name="reservation_list", methods={"GET"})
     */
    public function listres(ReservationRepository $reservationRepository): Response
    {
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);


        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('reservation/listres.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A3', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => false
        ]);
    }


    /**
     * @Route("/new", name="reservation_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reservation_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_delete", methods={"POST"})
     */
    public function delete(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
<table>
    <tr>
        <td>{{ form_label(form.FLYING_FROM, "Flying From") }}</td>
        <td>{{ form_widget(form.FLYING_FROM) }}</td>
        <td>{{ form_errors(form.FLYING_FROM) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.FLYING_TO, "Flying To") }}</td>
        <td>{{ form_widget(form.FLYING_TO) }}</td>
        <td>{{ form_errors(form.FLYING_TO) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.DEPARTING, "Departing ") }}</td>
        <td>{{ form_widget(form.DEPARTING) }}</td>
        <td>{{ form_errors(form.DEPARTING) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.Retour, "Return ") }}</td>
        <td>{{ form_widget(form.Retour) }}</td>
        <td>{{ form_errors(form.Retour) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.adults, "Adults ") }}</td>
        <td>{{ form_widget(form.adults) }}</td>
        <td>{{ form_errors(form.adults) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.children, "Children ") }}</td>
        <td>{{ form_widget(form.children) }}</td>
        <td>{{ form_errors(form.children) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.phone, "Phone ") }}</td>
        <td>{{ form_widget(form.phone) }}</td>
        <td>{{ form_errors(form.phone) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.travel_class, "Travel Class ") }}</td>
        <td>{{ form_widget(form.travel_class) }}</td>
        <td>{{ form_errors(form.travel_class) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.voyage, "Trip ") }}</td>
        <td>{{ form_widget(form.voyage) }}</td>
        <td>{{ form_errors(form.voyage) }}</td>
    </tr>


</table>
{{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends'Front_Office/Header-Footer.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

  {% block Content %}
      <br> <br><br><br> <br> <br>
      <h2 style="text-align:center" class="subtitle text-primary">Edit your trip</h2>
    <section class="py-lg-5">
        <div class="container">

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}
          <div class="col text-center text-sm-left"><a class="btn btn-link text-muted" href="{{ path('reservation_index') }}">
              <i class="fa-chevron-left fa mr-2"></i> Cancel
            </a>
          </div>
        </div>
    </section>

    <br><br><br><br><br>



{% endblock %}

templates/reservation/index.html.twig
{% extends'Front_Office/Header-Footer.html.twig' %}

 {% block title %}
     Trips
 {% endblock %}


    {% block Content %}
        <br> <br><br><br> <br> <br>
        <section class="d-flex align-items-center dark-overlay bg-cover" style="background-image: url('{{ asset('front-office/img/photo/trip1.jpg') }}');">
            <div class="container py-6 py-lg-7 text-white overlay-content text-center">
                <div class="row">
                    <div class="col-xl-10 mx-auto">
                        <h1 class="display-3 font-weight-bold text-shadow">Tabaani Trips</h1>
                        <p class="text-lg text-shadow">Let's Go</p>
                    </div>
                </div>
            </div>
        </section>
        <div class="container">
            <div class="search-bar rounded p-3 p-lg-4 position-relative mt-n5 z-index-20">
                <form id="searchForm" action="#">
                    <div class="row">
                        <div class="col-lg-4 d-flex align-items-center form-group">
                            <input class="form-control border-0 shadow-0" type="search" name="search" placeholder="Which trip are you searching for?">

                        </div>
                        <div class="col-lg-2 form-group mb-0">
                            <button class="btn btn-primary btn-block h-100" type="submit">Search </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
<section class="py-6">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-8">
                <p class="subtitle text-primary">The latest events</p>
                <h2>What's new on Tabaani</h2>
            </div>


            <div class="text-center">
                <a class="btn btn-outline-primary btn-block" href="{{ path('reservation_new') }}">
                    <i class="far fa-paper-plane mr-2"></i>
                    Book now
                </a>
            </div>
        </div>


        <h1>Reservation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>FLYING FROM</th>
                <th>FLYING TO</th>
                <th>DEPARTING</th>
                <th>Return</th>
                <th>Adults</th>
                <th>Children</th>
                <th>Phone</th>
                <th>Travel Class</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.FLYINGFROM }}</td>
                <td>{{ reservation.FLYINGTO }}</td>
                <td>{{ reservation.DEPARTING ? reservation.DEPARTING|date('Y-m-d') : '' }}</td>
                <td>{{ reservation.Retour ? reservation.Retour|date('Y-m-d') : '' }}</td>
                <td>{{ reservation.adults }}</td>
                <td>{{ reservation.children }}</td>
                <td>{{ reservation.phone }}</td>
                <td>{{ reservation.travelClass }}</td>
                <td>
                    <a href="{{ path('reservation_show', {'id': reservation.id}) }}">show</a>
                    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('reservation_new') }}">Create new</a>
    </div>
</section>
{% endblock %}

templates/reservation/listres.html.twig
    {% block Content %}

                <h1>Reservation index</h1>

                <table class="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>FLYING FROM</th>
                        <th>FLYING TO</th>
                        <th>DEPARTING</th>
                        <th>Return</th>
                        <th>Adults</th>
                        <th>Children</th>
                        <th>Phone</th>
                        <th>Travel Class</th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for reservation in reservations %}
                        <tr>
                            <td>{{ reservation.id }}</td>
                            <td>{{ reservation.FLYINGFROM }}</td>
                            <td>{{ reservation.FLYINGTO }}</td>
                            <td>{{ reservation.DEPARTING ? reservation.DEPARTING|date('Y-m-d') : '' }}</td>
                            <td>{{ reservation.Retour ? reservation.Retour|date('Y-m-d') : '' }}</td>
                            <td>{{ reservation.adults }}</td>
                            <td>{{ reservation.children }}</td>
                            <td>{{ reservation.phone }}</td>
                            <td>{{ reservation.travelClass }}</td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>


    {% endblock %}

templates/reservation/new.html.twig
{% extends'Front_Office/Header-Footer.html.twig' %}

 {% block title %}
     Trips
 {% endblock %}


    {% block Content %}
        <br> <br><br><br> <br> <br>
<h2 style="text-align:center" class="subtitle text-primary">Let's Book</h2>
<section class="py-lg-5">
    <div class="container">
        <h1 class="h2 mb-5"> Informations       </h1>
    {{ include('reservation/_form.html.twig') }}

        <div class="col text-center text-sm-left"><a class="btn btn-link text-muted" href="{{ path('reservation_index') }}">
                <i class="fa-chevron-left fa mr-2"></i> Cancel
            </a>
        </div>
    </div>
</section>

        <br><br><br><br><br>
{% endblock %}

templates/reservation/show.html.twig
{% extends'Front_Office/Header-Footer.html.twig' %}

 {% block title %}
     Trips
 {% endblock %}


    {% block Content %}
        <br> <br><br><br> <br> <br>
<h2 style="text-align:center" class="subtitle text-primary">Your details</h2>
<section class="py-lg-5">
    <div class="container">
        <h1 class="h2 mb-5"> Informations       </h1>
        <a href="{{ path('reservation_list') }}" class="btn btn-primary font-weight-bolder">
						<span class="svg-icon svg-icon-md">
							<!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
							<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
								<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
									<rect x="0" y="0" width="24" height="24" />
										<circle fill="#000000" cx="9" cy="15" r="6" />
											<path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
								</g>
							</svg>
                            <!--end::Svg Icon-->
						</span>Print</a>
        <br> <br> <br>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>FLYING FROM</th>
                <td>{{ reservation.FLYINGFROM }}</td>
            </tr>
            <tr>
                <th>FLYING TO</th>
                <td>{{ reservation.FLYINGTO }}</td>
            </tr>
            <tr>
                <th>DEPARTING</th>
                <td>{{ reservation.DEPARTING ? reservation.DEPARTING|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Return</th>
                <td>{{ reservation.Retour ? reservation.Retour|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Adults</th>
                <td>{{ reservation.adults }}</td>
            </tr>
            <tr>
                <th>Children</th>
                <td>{{ reservation.children }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ reservation.phone }}</td>
            </tr>
            <tr>
                <th>Travel Class</th>
                <td>{{ reservation.travelClass }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reservation_index') }}">back to list</a>

    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservation/_delete_form.html.twig') }}
    </div>
</section>

        <br><br><br><br><br>
{% endblock %}