src/Entity/Promotion.php
<?php

namespace App\Entity;

use App\Repository\PromotionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PromotionRepository::class)
 */
class Promotion
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $pourcent_prom;

    /**
     * @ORM\OneToOne(targetEntity=Voyage::class, inversedBy="promotion", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $voyage;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPourcentProm(): ?float
    {
        return $this->pourcent_prom;
    }

    public function setPourcentProm(float $pourcent_prom): self
    {
        $this->pourcent_prom = $pourcent_prom;

        return $this;
    }

    public function getVoyage(): ?Voyage
    {
        return $this->voyage;
    }

    public function setVoyage(Voyage $voyage): self
    {
        $this->voyage = $voyage;

        return $this;
    }
}

src/Form/PromotionType.php
<?php

namespace App\Form;

use App\Entity\Promotion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PromotionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('pourcent_prom')
            ->add('voyage')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Promotion::class,
        ]);
    }
}

src/Controller/PromotionController.php
<?php

namespace App\Controller;

use App\Entity\Promotion;
use App\Form\PromotionType;
use App\Repository\PromotionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;

/**
 * @Route("/promotion")
 */
class PromotionController extends AbstractController
{
    /**
     * @Route("/", name="promotion_index", methods={"GET"})
     */
    public function index(PromotionRepository $promotionRepository, Request $request, PaginatorInterface $paginator): Response
    {
        // Méthode findBy qui permet de récupérer les données avec des critères de filtre et de tri
        $donnees = $this->getDoctrine()->getRepository(Promotion::class)->findBy([],['pourcent_prom' => 'desc']);

        $promotion = $paginator->paginate(
            $donnees,
            $request->query->getInt('page', 1),
            3
        );

        return $this->render('promotion/index.html.twig', [
            'promotions' => $promotion,
        ]);
    }

    /**
     * @Route("/new", name="promotion_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $promotion = new Promotion();
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($promotion);
            $entityManager->flush();

            return $this->redirectToRoute('promotion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('promotion/new.html.twig', [
            'promotion' => $promotion,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="promotion_show", methods={"GET"})
     */
    public function show(Promotion $promotion): Response
    {
        return $this->render('promotion/show.html.twig', [
            'promotion' => $promotion,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="promotion_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Promotion $promotion, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('promotion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('promotion/edit.html.twig', [
            'promotion' => $promotion,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="promotion_delete", methods={"POST"})
     */
    public function delete(Request $request, Promotion $promotion, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$promotion->getId(), $request->request->get('_token'))) {
            $entityManager->remove($promotion);
            $entityManager->flush();
        }

        return $this->redirectToRoute('promotion_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/promotion/_delete_form.html.twig
<form method="post" action="{{ path('promotion_delete', {'id': promotion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ promotion.id) }}">
    <button class="btn">Delete</button>
</form>

templates/promotion/_form.html.twig
{{ form_start(form) }}

<table>
    <tr>
        <td>{{ form_label(form.pourcent_prom, "Trip Name") }}</td>
        <td>{{ form_widget(form.pourcent_prom) }}</td>
        <td>{{ form_errors(form.pourcent_prom) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.voyage, "Trip Name") }}</td>
        <td>{{ form_widget(form.voyage) }}</td>
        <td>{{ form_errors(form.voyage) }}</td>
    </tr>

</table>
{{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/promotion/edit.html.twig
{% extends 'Back_Office/AdminMain.html.twig' %}

{% block title %}Edit Promotion{% endblock %}

{% block Entry %}
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <div class="card card-custom gutter-b example example-compact">
                <div class="card-header">
                    <h3 class="card-title">Edit a Promotion</h3>
                </div>

                <div class="card-body">

    {{ include('promotion/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('promotion_index') }}">back to list</a>


                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/promotion/index.html.twig
{% extends 'Back_Office/AdminMain.html.twig' %}

{% block title %}Promotion index{% endblock %}

{% block Entry %}
<div class="container">
<div class="card card-custom gutter-b">
    <div class="card-header flex-wrap py-3">
        <div class="card-title">
            <h3 class="card-label">Promotions Details
                <span class="d-block text-muted pt-2 font-size-sm">The full promotion</span></h3>
        </div>
        <a href="{{ path('promotion_new') }}" class="btn btn-primary font-weight-bolder">
						<span class="svg-icon svg-icon-md">
							<!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
							<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
								<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
									<rect x="0" y="0" width="24" height="24" />
										<circle fill="#000000" cx="9" cy="15" r="6" />
											<path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
								</g>
							</svg>
                            <!--end::Svg Icon-->
						</span>New Promotion</a>
        <nav aria-label="Page navigation example">
            <ul class="pagination pagination-template d-flex justify-content-center">
                <li class="page-item">
                    {{ knp_pagination_render(promotions) }}
                </li>
            </ul>
        </nav>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Pourcent_prom</th>
                <th>Voyage</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for promotion in promotions %}
            <tr>
                <td>{{ promotion.id }}</td>
                <td>{{ promotion.pourcentProm }}</td>
                <td>{{ promotion.voyage }}</td>
                <td>
                    <a href="{{ path('promotion_show', {'id': promotion.id}) }}">show</a>
                    <a href="{{ path('promotion_edit', {'id': promotion.id}) }}">edit</a>
                    <a class="btn btn-clean ">
                        {{ include('promotion/_delete_form.html.twig') }}
                    </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    </div>
</div>
</div>
{% endblock %}

templates/promotion/new.html.twig
{% extends 'Back_Office/AdminMain.html.twig' %}
{% block title %}New Promotion{% endblock %}


   {% block Entry %}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="card card-custom gutter-b example example-compact">
                <div class="card-header">
                    <h3 class="card-title">Add a promotion</h3>
                </div>

                <div class="card-body">

                    {{ include('promotion/_form.html.twig') }}

                    <a href="{{ path('promotion_index') }}">back to list</a>
                </div>

                </div>
            </div>
        </div>
    </div>
       <br><br><br><br><br>
{% endblock %}

templates/promotion/show.html.twig
{% extends 'Back_Office/AdminMain.html.twig' %}

{% block title %}Promotion{% endblock %}

{% block Entry %}


    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-25 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Table Trips</h4>
                            <h5 class="card-description">
                                List Trips
                            </h5>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Pourcent_prom</th>




                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>{{ promotion.id }}</td>
                                        <td>{{ promotion.pourcentProm }}</td>



                                    </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>




            </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:../../partials/_footer.html -->

        <!-- partial -->
    </div>
    <!--end::Card-->
    </div>
    <!--end::Container-->
    </div>
    <!--end::Entry-->
    </div>
    <a href="{{ path('promotion_index') }}">back to list</a>

    <a href="{{ path('promotion_edit', {'id': promotion.id}) }}">edit</a>

    {{ include('promotion/_delete_form.html.twig') }}
{% endblock %}